---
Negative island analysis
---
```{r}
rm(list = ls())
library(tidyverse)
library(brms)
library(lme4)
library(lmerTest)
library(plotrix)
library(stringr)
library(readxl)

remove_na = function(x) {
  x[!is.na(x)]
}

d = read_csv("combined_results.csv") %>%
  select(-1, -2) %>%
  mutate(unk=unk == "True") %>%
  separate(condition, sep="_", into=c("wh", "gap", "island"))

d_agg = d %>% 
  group_by(model, region, sent_index, wh, gap, island) %>% 
    summarise(surprisal=sum(surprisal),
              unk=any(unk)) %>%
    ungroup() %>% 
  filter(!unk) %>%
  mutate(wh_numeric=if_else(wh == "what", 1, -1),
         wh=factor(wh, levels=c("what", "that")),
         gap=factor(gap, levels=c("no-gap", "gap")),
         island=factor(island, levels=c("pos", "neg")))


```





### Post-gap material

```{r}
d_wh_effect = d_agg %>%
  filter(region == "continuation") %>%
  select(-wh_numeric) %>%
  spread(wh, surprisal) %>%
  mutate(wh_effect=what-`that`) 

d_wh_effect %>% 
  group_by(model, gap, island) %>%
    summarise(m=mean(wh_effect),
              s=std.error(wh_effect),
              upper=m+1.96*s,
              lower=m-1.96*s) %>%
      ungroup() %>%
  ggplot(aes(x=island, y=m, ymin=lower, ymax=upper, fill=gap)) +
    geom_bar(stat="identity", position="dodge") +
  ylab("Surprisal with wh-phrase vs. without wh-phrase") +
    xlab("Polarity of Extraction Domain") +
  theme_bw(base_size=20) + 
    geom_errorbar(color="black", width=.5, position=position_dodge(width=.9)) +
    facet_wrap(~model) +
  ggsave("neg-sur.eps",height=8,width=8)
  
```


Contribution of each effect for the island conditions:

```{r}
d_contrib = d_agg %>%
  filter(region == "continuation") %>%
  select(-wh_numeric) %>%
  spread(wh, surprisal) %>%
  mutate(wh_effect=what-`that`) %>%
  select(-what, -that) %>%
  spread(gap, `wh_effect`) %>%
  mutate(wh_interaction = `no-gap`-gap) %>%
  mutate(`no-gap` = if_else(`no-gap` > 0, `no-gap`, 0)) %>%
  mutate(gap = if_else(gap < 0, gap, 0)) %>%
  mutate(gap_contrib = abs(gap) / (`no-gap`-gap))


d_contrib %>%
  group_by(model, island) %>%
    summarise(gap_contrib=mean(gap_contrib, na.rm=T),
              m=mean(wh_interaction, na.rm=T),
              s=std.error(wh_interaction, na.rm=T),
              upper=m+1.96*s,
              lower=m-1.96*s) %>%
    ungroup() %>%
  mutate(gap = m * gap_contrib) %>%
  mutate(no_gap = (1-gap_contrib) * m) %>%
  gather("gapped", "contribution", gap, no_gap) %>%
  ggplot(aes(x=island, y=contribution, ymin=lower, ymax=upper, fill=island, alpha=factor(gapped))) +
    scale_alpha_discrete(range=c(0.7, 1)) +
    geom_bar(stat="identity") +
    geom_errorbar(color="black", width=.5) +
    ylab("Licensing Interaction") +
    xlab("Location of Extraction Domain") +
    scale_x_discrete(labels= c("Object Position", "Adjunct Back", "Adjunct Front")) +
    theme(axis.text.x = element_text(angle=45, hjust=1)) +
    facet_wrap(~model) +
    ggtitle("Post-Gap Material")

```

The full licensing interaction:

```{r}
d_full_interaction = d_agg %>%
  filter(region == "continuation") %>%
  select(-wh_numeric) %>%
  spread(gap, surprisal) %>%
  mutate(gap_effect=`no-gap`-gap) %>%
  select(-unk, -gap, -`no-gap`) %>%
  spread(wh, gap_effect) %>%
  mutate(wh_interaction=what-`that`) %>%

  #Error Calculation
  #Across condition mean response
  group_by(model, sent_index) %>%
    mutate(across_condition_mean = mean(wh_interaction)) %>%
  ungroup() %>%
  #Item mean-extracted-response measure
  mutate(item_mean = wh_interaction - across_condition_mean) %>%
  #Across item item-mean error
  group_by(model, island) %>%
    mutate(err = std.error(item_mean, na.rm=T)) %>%
  ungroup() %>%
  select(-item_mean, -across_condition_mean)

```

Testing

```{R}
x = d_full_interaction %>% 
     filter(model == "google")

t.test(x$wh_interaction ~ x$island)

x = d_full_interaction %>% 
     filter(model == "gulordava")

t.test(x$wh_interaction ~ x$island)
```

Rest of the plot:

```{R}

d_full_interaction %>%
  group_by(model, island) %>%
    summarise(m=mean(wh_interaction, na.rm=T),
              s=mean(err),
              upper=m+1.96*s,
              lower=m-1.96*s) %>%
    ungroup() %>%
  ggplot(aes(x=island, y=m, ymin=lower, ymax=upper, fill=island)) +
    geom_bar(stat="identity") +
    geom_errorbar(color="black", width=.5, position=position_dodge(width=.9)) +
    theme(legend.position="none") +
    ylab("Licensing Interaction") +
    xlab("Location of Extraction Domain") +
    theme(axis.text.x = element_text(angle=45, hjust=1)) +
    facet_wrap(~model) +
    ggtitle("Post-Gap Material")
```

